services:
  ######################################################
  # R Testing
  ######################################################
  r-test:
    image: r-package/R6P
    build:
      context: ./
      dockerfile: ./.dev/docker/r-test/Dockerfile
    entrypoint: '/bin/bash'
    container_name: r_test
    restart: "no"
  ######################################################
version: "3.8"
