name: R-CMD-check

on:
  # Trigger on pushes and pull requests.
  push:
  pull_request:

jobs:
  check:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        # Operating systems and R versions to test.
        config:
          - {os: ubuntu-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'devel'}
          - {os: macOS-latest, r: 'release'}
          - {os: windows-latest, r: 'release'}

    steps:
      - uses: actions/checkout@v3
        # Checks out repository code.

      - uses: r-lib/actions/setup-r@v2
        # Installs the R version specified in the matrix.
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        # Installs core dependencies from CRAN.
        with:
          dependencies: all

      - uses: r-lib/actions/setup-pandoc@v2
        # Makes pandoc available for R Markdown tasks.

      - uses: r-lib/actions/setup-r-dependencies@v2
        # Installs additional R packages.
        with:
          extra-packages: devtools rcmdcheck rmarkdown testthat

      - uses: r-lib/actions/check-r-package@v2
        # Executes R CMD check on the package.
        with:
          build-args: --as-cran
